on:
  push:
    branches:
      - main

name: 🚀 Deploy api on push (Main)
jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: 🔨 Install dependencies
        run: composer install --prefer-dist --no-progress

      # - name: 🔑 Set .env campobase
      #   run: cp -f .env.campobase .env

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with:
          server: ftp.llamadev.cl
          username: gh-devmanager-api@llamadev.cl
          password: ${{ secrets.ftp_password }}
          exclude: |
            **/.git*
            **/.git*/**
            **/storage/**
            **/public/**

      # - name: 🔑 Set .env mamatierra
      #   run: cp -f .env.mamatierra .env

      # - name: 📂 Sync files mamatierra
      #   uses: SamKirkland/FTP-Deploy-Action@4.3.0
      #   with:
      #     server: ftp.hostalmamatierra.cl
      #     username: gh-cashflow-api@hostalmamatierra.cl
      #     password: ${{ secrets.ftp_password_mamatierra }}
      #     exclude: |
      #       **/.git*
      #       **/.git*/**
      #       **/storage/**
      #       **/public/**

      # - name: 🔑 Set .env belen
      #   run: cp -f .env.belen .env

      # - name: 📂 Sync files belen
      #   uses: SamKirkland/FTP-Deploy-Action@4.3.0
      #   with:
      #     server: ftp.hostalbelen.cl
      #     username: gh-cashflow-api@hostalbelen.cl
      #     password: ${{ secrets.ftp_password_belen }}
      #     exclude: |
      #       **/.git*
      #       **/.git*/**
      #       **/storage/**
      #       **/public/**
      #       .env.campobase
      #       .env.mamatierra
      #       .env.belen
